all:
	gcc decdate.c -o decdate
	gcc incdate.c -o incdate
	g++ diffdate.cpp -o diffdate
	g++ dateplusdays.cpp -o dpd
	g++ findmaxtime.cpp -o findmaxtime

clean:
	rm decdate
	rm incdate
	rm diffdate
	rm dpd
	rm findmaxtime
