all:
	gcc dtos.c -o dtos
	gcc decdate.c -o decdate
	gcc nametodate.c -o ntod
	gcc incdate.c -o incdate
	g++ diffdate.cpp -o diffdate
	g++ dateplusdays.cpp -o dpd
	g++ findmaxtime.cpp -o findmaxtime

clean:
	rm dtos
	rm decdate
	rm ntod
	rm incdate
	rm diffdate
	rm dpd
	rm findmaxtime
